import {refs,db} from './firebase.js';
import {store} from './store.js';
import {uid,now} from './core.js';
const arr=v=>Array.isArray(v)?v:Object.values(v||{});
export async function legacyStatus(){if(!store.isAdmin)return null;const s=await refs.legacy.once('value');const d=s.val()||{};return {exists:s.exists(),cars:arr(d.cars).length,owners:arr(d.owners).length,renters:arr(d.renters).length,bookings:arr(d.bookings).length}}
export async function migrateLegacy(){if(!store.isAdmin)throw Error('מנהל בלבד');const s=await refs.legacy.once('value'),d=s.val();if(!d)throw Error('לא נמצאו נתונים ישנים');const updates={};const usersByLegacy={};for(const u of [...arr(d.owners).map(x=>({...x,role:'owner'})),...arr(d.renters).map(x=>({...x,role:'renter'}))]){const firebaseUid=u.uid||u.firebaseUid;if(!firebaseUid)continue;usersByLegacy[u.id||firebaseUid]=firebaseUid;updates[`users/${firebaseUid}`]={name:u.name||'',email:u.email||'',phone:u.phone||'',role:u.role,createdAt:u.createdAt||now(),verification:{email:!!u.verification?.email,licenseFront:!!u.verification?.licenseFront,licenseBack:!!u.verification?.licenseBack,selfie:!!u.verification?.selfie}};updates[`verificationStatus/${firebaseUid}`]=u.verification?.status||'missing'}
for(const c of arr(d.cars)){const id=String(c.id||uid());const ownerUid=c.ownerUid||c.ownerId&&usersByLegacy[c.ownerId];if(!ownerUid)continue;updates[`cars/${id}`]={make:c.make||'',model:c.model||'',year:c.year||'',trim:c.trim||'',ownerUid,status:c.status||'available',dailyPrice:Number(c.dailyPrice||c.price||0),minAge:Number(c.minAge||21),area:c.area||c.location||'Crown Heights',deliveryEnabled:!!c.deliveryEnabled,photoUrl:Array.isArray(c.photos)?c.photos[0]||'':c.photoUrl||'',createdAt:c.createdAt||now()}}
for(const b of arr(d.bookings)){const id=String(b.id||uid()),ownerUid=b.ownerUid||b.ownerId&&usersByLegacy[b.ownerId],renterUid=b.renterUid||b.renterId&&usersByLegacy[b.renterId];if(!ownerUid||!renterUid)continue;updates[`bookings/${id}`]={carId:String(b.carId||''),ownerUid,renterUid,startAt:b.startAt||b.from||'',endAt:b.endAt||b.to||'',status:b.done?'done':b.status||'pending',done:!!b.done,createdAt:b.createdAt||now()}}
updates['migration/v2']={completedAt:now(),source:'crowndrive-live/state/data'};await db.ref().update(updates);return Object.keys(updates).length}
